### PR TITLE
MAT-317: Remove Donation.clientSecret property

### PR DESCRIPTION
**Pull request by bdsl**
Not needed in future when donations are always confirmed from matchbot not from the client

** DO NOT MERGE UNTIL AFTER https://github.com/thebiggive/donate-frontend/pull/1302 IS DEPLOYED TO PROD **

### CODE REVIEW

**Review by NoelLH — COMMENTED** [review]
Looks like Psalm's still unhappy but the basic idea looks good

**Comment by bdsl** [comment]
> Looks like Psalm's still unhappy but the basic idea looks good

Thanks, fixed the Psalm issue.

**Review by NoelLH — APPROVED** [review]
Looks good!

I don't think we made the full scope of the tidying explicit in Jira but perhaps we should also at this point stop calling `$this->donationRepository->deriveFees()` in the `Update` action? Unless that's going to cause more trouble with Donation Funds when we use `autoConfirmFromCashBalance` in an Update.

**Comment by bdsl** [comment]
> perhaps we should also at this point stop calling `$this->donationRepository->deriveFees()` in the `Update` action? Unless that's going to cause more trouble with Donation Funds when we use `autoConfirmFromCashBalance` in an Update.

Yes probably. I've copied your question and this answer to Jira.

**Pull request merged**
